noise_dim: 128
seed: 277
n_g: 1
n_d: 8
epochs: 50
grad_penalty_lambda: 10

D_model:
    name: "C"
    parameters:
        image_channels: 3
        base_channels: 64
        dropout_rate: 0.0
        sn: False
        neg_slope: 0.2
        norm: "layer"
        patch: True # very usefull: additional saptial information + bigger penalties for gradients

G_model:
    name: "WG"
    parameters:
        n_z: 128
        image_size: 512
        image_channels: 3
        base_channels: 512


D_optimizer:
    name: "Adam"
    parameters:
        lr: 0.0003
        betas: [0., 0.9]


G_optimizer:
    name: "Adam"
    parameters:
        lr: 0.0001
        betas: [0., 0.9]

loss:
    name: "Wasserstein"
    parameters: {}


# Conclusions: 
#   - gradients is finally perfect and not exploded (avg_gN=1.7, avg_dN=5.4)
#   - loss is small, especially for Critic
#   - the best config. the key here is to not overregularize Critic.