noise_dim: 128
seed: 17
n_g: 2      # change if equilibrium can not be converged
epochs: 50  # only 50 for experiments
G_max_norm: 3
D_max_norm: 5

D_model:
    name: "D"
    parameters:
        image_size: 512
        image_channels: 3
        base_channels: 64
        dropout_rate: 0.0   # turn on if overfitting
        sn:  False          # should be tried
        neg_slope: 0.2
        norm: "instance"    # 'batch' | 'none'
        patch: False        # should be tried

G_model:
    name: "baseline_G"      # "G" (advanced) must be tried
    parameters:
        n_z: 128
        image_size: 512
        image_channels: 3
        base_size: 8
        base_channels: 512


D_optimizer:
    name: "AdamW"
    parameters:
        lr:  0.0007         # different lr should be tried 
        betas: [0.9, 0.999]
        weight_decay: 0
        amsgrad: False

G_optimizer:
    name: "AdamW"
    parameters:
        lr:  0.0007         # different lr should be tried 
        betas: [0.9, 0.999]
        weight_decay: 0
        amsgrad: False


loss:
    name: "BCE"             # "Wasserstein" | "Hinge"
    parameters: {}


# Conclusions: 
#   - D is stronger then G
#   - G too weak; n_g is small, lr is big