noise_dim: 128
seed: 17
n_g: 5
n_d: 1
epochs: 50  # only 50 for experiments
G_max_norm: 10
D_max_norm: 7

D_model:
    name: "D"
    parameters:
        image_channels: 3
        base_channels: 64
        dropout_rate: 0.4
        sn: False
        neg_slope: 0.2
        norm: "batch"
        patch: False

G_model:
    name: "G"
    parameters:
        n_z: 128
        image_size: 512
        image_channels: 3
        base_channels: 512


D_optimizer:
    name: "AdamW"
    parameters:
        lr:  0.00003
        betas: [0.5, 0.999]
        weight_decay: 0
        amsgrad: False

G_optimizer:
    name: "AdamW"
    parameters:
        lr:  0.0005
        betas: [0.5, 0.999]
        weight_decay: 0
        amsgrad: False


loss:
    name: "BCE"
    parameters:
        label_smoothing: 0.05


# Conclusions: 
#   - G is stronger and learns in 5 times more than D
#   - D optimized penalized by dropout and smaller lr
#   - gradient do not explode
#   - labels_smoothing is added
#   - unfortunately D is not that strong to classify real/fake properly -> G can't learn from D -> both of model weak (but it's better then previous configurations)
#   - if i want to find ideal balance i need to make D moderatly stronger and use wasserstain loss to optimize training