noise_dim: 128
seed: 277
n_g: 1
n_d: 5
epochs: 50
grad_penalty_lambda: 13

D_model:
    name: "C"
    parameters:
        image_channels: 3
        base_channels: 64
        dropout_rate: 0.0
        sn: False
        neg_slope: 0.2
        norm: "instance"
        patch: False

G_model:
    name: "WG"
    parameters:
        n_z: 128
        image_size: 512
        image_channels: 3
        base_channels: 512


D_optimizer:
    name: "Adam"
    parameters:
        lr: 0.0001
        betas: [0., 0.9]


G_optimizer:
    name: "Adam"
    parameters:
        lr: 0.0001
        betas: [0., 0.9]

loss:
    name: "Wasserstein"
    parameters: {}


# Conclusions: 