noise_dim: 128
seed: 277
n_g: 1
n_d: 5
epochs: 50
G_max_norm: 12
D_max_norm: 12

D_model:
    name: "C"
    parameters:
        image_channels: 3
        base_channels: 64
        dropout_rate: 0.0
        sn: True
        neg_slope: 0.2
        norm: "none"
        patch: False

G_model:
    name: "WG"
    parameters:
        n_z: 128
        image_size: 512
        image_channels: 3
        base_channels: 512


D_optimizer:
    name: "Adam"
    parameters:
        lr: 0.0001
        betas: [0., 0.9]


G_optimizer:
    name: "Adam"
    parameters:
        lr: 0.0001
        betas: [0., 0.9]

loss:
    name: "Wasserstein"
    parameters: {}


# Conclusions: 
#   - gradients is still big either for C and G (but smaller then in WGAN-wc)
#   - loss is negative for both C and G. G loss is big (~-750) C loss is smaller (~-5)
#   - C can't be learnt because of gradient explosion
#   - G can't learn from C because C is illiterate
#   - even if every part of C model is wrapped in spectral norm, lipschitz constrain can not be reached fully but it's still better the weight clipping