noise_dim: 128
seed: 277
n_g: 1
n_d: 5
epochs: 50
weight_clip: 0.02
G_max_norm: 12
D_max_norm: 12

D_model:
    name: "C"
    parameters:
        image_channels: 3
        base_channels: 64
        dropout_rate: 0.0
        sn: False
        neg_slope: 0.2
        norm: "none"
        patch: False

G_model:
    name: "WG"
    parameters:
        n_z: 128
        image_size: 512
        image_channels: 3
        base_channels: 512


D_optimizer:
    name: "RMSprop"
    parameters:
        lr: 0.0001

G_optimizer:
    name: "RMSprop"
    parameters:
        lr: 0.0001

loss:
    name: "Wasserstein"
    parameters: {}


# Conclusions: 
#   - gradients is enormous for both C and G (surly they become smaller over the time but not that much (from ~250_000_000 to ~5_000_000) and not monotonicly)
#   - loss is negative for both C and G and its magnitudes are very large
#   - C can't classify even the simplest images and output 1 every time
#   - G can't learn from C because C is broken
#   - possible cause - weight clipping -> C is suffering
#   - lipschitz constrain can not be reached -> main and the most obvious poroblem